<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeds = [
            [
                'id' => 1,
                'username' => 'milos.admin',
                'password' => Hash::make('milos.admin'),
                'first_name' => 'Milos',
                'last_name' => 'Milosevic',
                'email' => 'milos.admin@gmail.com',
                'phone_number' => '067000001',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'username' => 'vladimir.admin',
                'password' => Hash::make('vladimir.admin'),
                'first_name' => 'Vladimir',
                'last_name' => 'Vladimirovic',
                'email' => 'vladimir.admin@gmail.com',
                'phone_number' => '067000002',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'username' => 'mirko',
                'password' => Hash::make('mirko.test'),
                'first_name' => 'Mirko',
                'last_name' => 'Markovic',
                'email' => 'mirko@gmail.com',
                'phone_number' => '067000003',
                'gender' => 'Male',
                'country' => 'Bosnia and Herzegovina',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'username' => 'kristijan.manager',
                'password' => Hash::make('kristijan.manager'),
                'first_name' => 'Kristijan',
                'last_name' => 'Popovic',
                'email' => 'kristijan.manager@gmail.com',
                'phone_number' => '067000004',
                'gender' => null,
                'country' => 'Serbia',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'username' => 'serdjo.manager',
                'password' => Hash::make('serdjo.manager'),
                'first_name' => 'Serdjo',
                'last_name' => 'Srdanovic',
                'email' => 'serdjo.manager@gmail.com',
                'phone_number' => '067000005',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'username' => 'zoran.auctioneer',
                'password' => Hash::make('zoran.auctioneer'),
                'first_name' => 'Zoran',
                'last_name' => 'Zoranovic',
                'email' => 'zoran.auctioneer@gmail.com',
                'phone_number' => '067000006',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'username' => 'petar.auctioneer',
                'password' => Hash::make('petar.auctioneer'),
                'first_name' => 'Petar',
                'last_name' => 'Petrovic',
                'email' => 'petar.auctioneer@gmail.com',
                'phone_number' => '067000007',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'username' => 'luka.123',
                'password' => Hash::make('luka.123'),
                'first_name' => 'Luka',
                'last_name' => 'Lukic',
                'email' => 'luka.123@gmail.com',
                'phone_number' => '067000008',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'username' => 'lazar.123',
                'password' => Hash::make('lazar.123'),
                'first_name' => 'Lazar',
                'last_name' => 'Lazarevic',
                'email' => 'lazar.123@gmail.com',       // change this e-mail in order to test mailing functionality
                'phone_number' => '067000009',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'username' => 'nikola.123',
                'password' => Hash::make('nikola.123'),
                'first_name' => 'Nikola',
                'last_name' => 'Nikolic',
                'email' => 'nikola.123@gmail.com',
                'phone_number' => '067000010',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'username' => 'veselin.123',
                'password' => Hash::make('veselin.123'),
                'first_name' => 'Veselin',
                'last_name' => 'Veselinovic',
                'email' => 'veselin.123@gmail.com',
                'phone_number' => '067000011',
                'gender' => 'Male',
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'username' => 'ljubomir.admin',
                'password' => Hash::make('ljubomir.admin'),
                'first_name' => 'Ljubomir',
                'last_name' => 'Ljubomirovic',
                'email' => 'ljubomir.admin@gmail.com',
                'phone_number' => '067000012',
                'gender' => 'Male',
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ];

        DB::table('users')->insert($seeds);
    }
}
