<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeds = [
            [
                'id' => 1,
                'username' => 'vladimir.admin',
                'password' => Hash::make('vladimir.admin'),
                'first_name' => 'Vladimir',
                'last_name' => 'Gazivoda',
                'email' => 'vladimir.admin@gmail.com',
                'phone_number' => '067336363',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'username' => 'lazar.admin',
                'password' => Hash::make('lazar.admin'),
                'first_name' => 'Lazar',
                'last_name' => 'Lukic',
                'email' => 'lazar.admin@gmail.com',
                'phone_number' => '067000001',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'username' => 'staka.admin',
                'password' => Hash::make('staka.admin'),
                'first_name' => 'Vladimir',
                'last_name' => 'Stanjevic',
                'email' => 'staka.admin@gmail.com',
                'phone_number' => '067000012',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'username' => 'mirko',
                'password' => Hash::make('mirko.test'),
                'first_name' => 'Mirko',
                'last_name' => 'Test',
                'email' => 'mirko@gmail.com',
                'phone_number' => '067000003',
                'gender' => 'Male',
                'country' => 'Bosnia and Herzegovina',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'username' => 'maynard.manager',
                'password' => Hash::make('maynard.manager'),
                'first_name' => 'Maynard',
                'last_name' => 'James Keenan',
                'email' => 'maynard.manager@gmail.com',
                'phone_number' => '067000004',
                'gender' => null,
                'country' => 'United States',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'username' => 'petar.manager',
                'password' => Hash::make('petar.manager'),
                'first_name' => 'Petar',
                'last_name' => 'Radoman',
                'email' => 'petar.manager@gmail.com',
                'phone_number' => '067000005',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'username' => 'zoran.auctioneer',
                'password' => Hash::make('zoran.auctioneer'),
                'first_name' => 'Zoran',
                'last_name' => 'Kukulicic',
                'email' => 'zoran.auctioneer@gmail.com',
                'phone_number' => '067000006',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'username' => 'serdjo.auctioneer',
                'password' => Hash::make('serdjo.auctioneer'),
                'first_name' => 'Serdjo',
                'last_name' => 'Crevar',
                'email' => 'serdjo.auctioneer@gmail.com',
                'phone_number' => '067000007',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'username' => 'luka.123',
                'password' => Hash::make('luka.123'),
                'first_name' => 'Luka',
                'last_name' => 'Popovic',
                'email' => 'luka.123@gmail.com',
                'phone_number' => '067000008',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'username' => 'marcus.123',
                'password' => Hash::make('marcus.123'),
                'first_name' => 'Marcus',
                'last_name' => 'Aurelius',
                'email' => 'marcus.123@gmail.com',       // change this e-mail in order to test mailing functionality
                'phone_number' => '067000009',
                'gender' => null,
                'country' => 'Italy',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'username' => 'ridzaruto.123',
                'password' => Hash::make('ridza.123'),
                'first_name' => 'Nikola',
                'last_name' => 'Ristic',
                'email' => 'ridza.123@gmail.com',
                'phone_number' => '067000010',
                'gender' => null,
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'username' => 'evangeline.123',
                'password' => Hash::make('evangeline.123'),
                'first_name' => 'Evangeline',
                'last_name' => 'Harrington',
                'email' => 'evangeline.123@gmail.com',
                'phone_number' => '067000011',
                'gender' => 'Female',
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'username' => 'katya.123',
                'password' => Hash::make('katya.123'),
                'first_name' => 'Katya',
                'last_name' => 'Clay',
                'email' => 'katya.123@gmail.com',
                'phone_number' => '067000013',
                'gender' => 'Female',
                'country' => 'Montenegro',
                'is_active' => true,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ];

        DB::table('users')->insert($seeds);
    }
}
